name: Nodejs CI

on:
  # schedule:
  # - cron: '47 17 * * 1'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm run
      run: |
        npm i
        npm run lint --if-present
        npm run build --if-present
        npm test --if-present
      env:
        CI: true
        ENV: test
